---
dependencies:
- name: cert-manager
  alias: certmanager
  version: 1.4.0
  repository: https://charts.bitnami.com/bitnami
  condition: certmanager.enabled
- name: postgresql
  version: 16.3.4
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
- name: redis
  version: 20.6.1
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
- name: minio
  version: 14.10.3
  repository: https://charts.bitnami.com/bitnami
  condition: minio.enabled
- name: nginx-ingress-controller
  version: 11.6.0
  repository: https://charts.bitnami.com/bitnami
  condition: nginx-ingress.enabled
- name: clickhouse
  version: 7.1.3
  repository: https://charts.bitnami.com/bitnami
- name: rabbitmq
  version: 15.2.1
  repository: https://charts.bitnami.com/bitnami
