---
dependencies:
- name: cert-manager
  alias: certmanager
  version: 1.6.1
  repository: https://charts.jetstack.io
  condition: certmanager.enabled
- name: postgresql
  version: 10.13.14
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
- name: redis
  version: 15.6.4
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
- name: minio
  version: 9.2.5
  repository: https://charts.bitnami.com/bitnami
  condition: minio.enabled
- name: ingress-nginx
  version: 4.0.13
  repository: https://kubernetes.github.io/ingress-nginx
  condition: nginx-ingress.enabled
