---
dependencies:
- name: cert-manager
  alias: certmanager
  version: 1.7.2
  repository: https://charts.jetstack.io
  condition: certmanager.enabled
- name: postgresql
  version: 12.1.6
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
- name: redis
  version: 17.3.17
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
- name: minio
  version: 11.10.24
  repository: https://charts.bitnami.com/bitnami
  condition: minio.enabled
- name: ingress-nginx
  version: 4.4.0
  repository: https://kubernetes.github.io/ingress-nginx
  condition: nginx-ingress.enabled
