---
dependencies:
- name: cert-manager
  alias: certmanager
  version: 1.7.2
  repository: https://charts.jetstack.io
  condition: certmanager.enabled
- name: postgresql
  version: 13.1.5
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
- name: redis
  version: 18.2.0
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
- name: minio
  version: 12.8.18
  repository: https://charts.bitnami.com/bitnami
  condition: minio.enabled
- name: ingress-nginx
  version: 4.4.0
  repository: https://kubernetes.github.io/ingress-nginx
  condition: nginx-ingress.enabled
