---
dependencies:
- name: cert-manager
  alias: certmanager
  version: 1.7.1
  repository: https://charts.jetstack.io
  condition: certmanager.enabled
- name: postgresql
  version: 10.16.2
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
- name: redis
  version: 16.4.5
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
- name: minio
  version: 10.1.16
  repository: https://charts.bitnami.com/bitnami
  condition: minio.enabled
- name: ingress-nginx
  version: 4.0.18
  repository: https://kubernetes.github.io/ingress-nginx
  condition: nginx-ingress.enabled
