---
dependencies:
- name: cert-manager
  alias: certmanager
  version: 0.9.1
  repository: https://charts.jetstack.io
  condition: certmanager.enabled
- name: postgresql
  version: 11.10.0
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
- name: redis
  version: 12.1.1
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
- name: minio
  version: 4.1.0
  repository: https://charts.bitnami.com/bitnami
  condition: minio.enabled
- name: nginx-ingress
  version: 0.7.1
  repository: https://helm.nginx.com/stable
  condition: nginx-ingress.enabled
