kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-role
  namespace: {{ .Release.Namespace }}
rules:
 - apiGroups: ["*"]
   resources: ["namespaces", "services", "pods"]
   verbs: ["get", "list"]
 - apiGroups: ["*"]
   resources: ["pods/exec"]
   verbs: ["create"]
