{{- $host := ( index .Values.ingress.hosts 0 ) -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "robomotion-app.fullname" . }}
  annotations:
{{- if .Values.certmanager.enabled }}
    cert-manager.io/issuer: "{{ .Release.Name }}-issuer"
{{- end }}
{{ toYaml .Values.app.ingress.annotations | indent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.spec.ingressClassName }}
{{- if $host.tls }}
  tls:
  - hosts:
    - {{ $host.name }}
    secretName: {{ $host.tlsSecret }}
{{- end }}
  rules:
  - host: {{ $host.name | quote }}
    http:
      paths:
      - path: {{ .Values.app.ingress.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ template "robomotion-app.fullname" . }}
            port:
              number: 80

