apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "robomotion-app.fullname" . }}
  labels:
    app: {{ template "robomotion-app.fullname" . }}
    chart: {{ template "robomotion.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: {{ .Values.app.name }}
spec:
  selector:
    matchLabels:
      app: {{ template "robomotion-app.fullname" . }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "robomotion-app.fullname" . }}
    spec:
      containers:
      - name: {{ template "robomotion-app.fullname" . }}
        image: "{{ .Values.app.image }}:{{ .Values.app.imageTag }}"
        ports:
        - containerPort: 80
          name: http
        env:    
          - name: APP_PATH
            value: {{ .Values.app.ingress.path }}
          - name: REDIS_SCHEME
            value: {{ default "redis" .Values.redis.scheme }}
          - name: REDIS_HOST
          {{- if .Values.redis.enabled }}
            value: {{ template "robomotion.redis.host" . }}
          {{- else }}
            value: {{ .Values.externalRedis.host | quote }}
          {{- end }}
          - name: REDIS_PORT
          {{- if .Values.redis.enabled }}
            value: {{ .Values.redis.redisPort | quote }}
          {{- else }}
            value: {{ .Values.externalRedis.port | quote }}
          {{- end }}
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                {{- if .Values.redis.enabled }}
                name: {{ template "robomotion.redis.fullname" . }}
                key: redis-password
                {{- else }}
                name: {{ printf "%s-%s" .Release.Name "external-redis"  }}
                key: password
                {{- end }}
          - name: RABBIT_USERNAME
            valueFrom:
              secretKeyRef:
                name: rabbit-default-user
                key: username
          - name: RABBIT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rabbit-default-user
                key: password
      {{- if .Values.registry.secret }}
      imagePullSecrets:
      - name: {{ .Values.registry.secret }}
      {{- end }}
