{{- $host := ( index .Values.ingress.hosts 0 ) -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "robomotion-auth.fullname" . }}
  annotations:
{{- if .Values.certmanager.enabled }}
    certmanager.k8s.io/issuer: "{{ .Release.Name }}-issuer"
{{- end }}
    nginx.ingress.kubernetes.io/ssl-redirect: {{ $host.tls | quote }}
{{ toYaml .Values.ingress.annotations | indent 4 }}
spec:
  {{ if $host.tls }}
  tls:
  - hosts:
    - {{ $host.name }}
    secretName: {{ $host.tlsSecret }}
  {{ if $host.multiTenant }}
  - hosts:
    - "*.{{ $host.name }}"
    secretName: {{ $host.wildSecret }}
  {{ end }}
  {{ end }}
  rules:
  - host: {{ $host.name | quote }}
    http:
      paths:
      - path: {{ .Values.auth.ingress.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ template "robomotion-auth.fullname" . }}
            port:
              number: 80
{{ if $host.multiTenant }}
  - host: "*.{{ $host.name }}"
    http:
      paths:
      - path: {{ .Values.auth.ingress.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ template "robomotion-auth.fullname" . }}
            port:
              number: 80
{{ end }}
