{{- $host := ( index .Values.ingress.hosts 0 ) -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "robomotion-bots.fullname" . }}
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: default-http-redirect@kubernetescrd
{{- if .Values.certmanager.enabled }}
    cert-manager.io/issuer: "{{ .Release.Name }}-issuer"
{{- end }}
    nginx.ingress.kubernetes.io/ssl-redirect: {{ $host.tls | quote }}
spec:
  ingressClassName: {{ .Values.ingress.spec.ingressClassName }}
{{- if $host.tls }}
  tls:
  - hosts:
    - {{ $host.name }}
    secretName: {{ $host.tlsSecret }}
{{- end }}
  rules:
  - host: {{ .Values.api.ingress.hostname | default $host.name }}
    http:
      paths:
      - path: {{ .Values.bots.ingress.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ template "robomotion-bots.fullname" . }}
            port:
              number: 80
