{{- $host := ( index .Values.ingress.hosts 0 ) -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: robomotion-bots-proxy
  annotations:
    kubernetes.io/ingress.class: "public"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - {{ $host.name }}
    secretName: wildcard-robomotion-letsencrypt
  rules:
  - host: {{ .Values.api.ingress.hostname | default $host.name }}
    http:
      paths:
      - path: /assistant
        pathType: Prefix
        backend:
          service:
            name: robomotion-bots-proxy
            port: 
              number: 80
