apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: {{ .Release.Name | quote }}
spec:
  defaults:
    templates:
      dataVolumeClaimTemplate: data-volume-template
      logVolumeClaimTemplate: log-volume-template
  configuration:
    clusters:
      - name: "ch"
        layout:
          shardsCount: 1
          replicasCount: 1
    users:
      admin/k8s_secret_password_sha256_hex: {{ printf "%s/%s-%s/%s" "default" .Release.Name "clickhouse" "passwordHex"  }}
      admin/networks/host_regexp: "(.*)$"
      admin/networks/ip: "127.0.0.1/32"
      admin/profile: admin_profile
      admin/quota: default
    profiles:
      admin_profile/async_insert: 1
      admin_profile/wait_for_async_insert: 1
    settings:
      compression/case/method: zstd
      disable_internal_dns_cache: 1
  templates:
    volumeClaimTemplates:
      - name: data-volume-template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: {{ .Values.clickhouse.persistence.data.size }}
      - name: log-volume-template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: {{ .Values.clickhouse.persistence.log.size }}