apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" .Release.Name "migrations-clickhouse"  }}
  labels:
    app: {{ printf "%s-%s" .Release.Name "migrations-clickhouse"  }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ printf "%s-%s" .Release.Name "migrations-clickhouse"  }}
