{{- $password := ( randAlphaNum 8 ) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Release.Name "clickhouse"  }}
  labels:
    app: {{ printf "%s-%s" .Release.Name "clickhouse"  }}
    chart: {{ template "robomotion.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  password: {{ $password | b64enc | b64enc | quote }}
  passwordHex: {{ $password | b64enc | sha256sum | b64enc | quote }}
