apiVersion: v1
kind: Service
metadata:
  name: {{ template "robomotion-cloudproxy.fullname" . }}
  labels:
    app: {{ template "robomotion-cloudproxy.fullname" . }}
spec:
  type: ClusterIP
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: {{ template "robomotion-cloudproxy.fullname" . }}
