apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: cloudbot
    namespace: default
rules:
    - apiGroups:
        - ''
      resources:
        - 'pods'
      verbs:
        - 'create'
        - 'delete'
        - 'get'
        - 'list'
        - 'patch'
