{{- $host := ( index .Values.ingress.hosts 0 ) -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "robomotion-designer.fullname" . }}
  annotations:
{{- if .Values.certmanager.enabled }}
    certmanager.k8s.io/issuer: "{{ .Release.Name }}-issuer"
{{- end }}
    nginx.ingress.kubernetes.io/ssl-redirect: {{ $host.tls | quote }}
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{ toYaml .Values.designer.ingress.annotations | indent 4 }}
spec:
{{- if $host.tls }}
  tls:
  - hosts:
  {{- if $host.multiTenant }}
    - secretName: {{ $host.wildSecret }}
  {{- else -}}
    - secretName: {{ $host.tlsSecret }}
  {{- end }}
{{- end }}
  rules:
{{- if $host.multiTenant }}
  - host: "*.{{ $host.name }}"
{{- else -}}
  - host: "{{ $host.name }}"
{{- end }}
    http:
      paths:
      - path: {{ .Values.designer.ingress.path }}
        backend:
          serviceName: {{ template "robomotion-designer.fullname" . }}
          servicePort: 80
