apiVersion: v1
data:
  alert_notification_example.html: |
    <!DOCTYPE html>
    <html>
    <body>

    <h1>Robomotion</h1>

    <p>My first paragraph.</p>

    </body>
    </html>
kind: ConfigMap
metadata:
  name: emails
  namespace: default

