apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentd
  {{- if .Values.externalLogging.override }}
  namespace: default
  {{- else }}
  namespace: kube-logging
  {{- end }}
  labels:
    k8s-app: fluentd-logging
    version: v1
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-logging
      version: v1
  template:
    metadata:
      labels:
        k8s-app: fluentd-logging
        version: v1
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd
        image: gcr.io/robomotion/fluentd:latest
        env:
          {{- if .Values.externalLogging.override }}
          - name: POSTGRES_HOST
            {{- if .Values.externalLogging.host }}
            value: {{ .Values.externalLogging.host }}
            {{- else }}
            value: {{ template "robomotion.postgresql.fullname" . }}
            {{- end }}
          - name: POSTGRES_PORT
            {{- if .Values.externalLogging.port }}
            value: {{ .Values.externalLogging.port }}
            {{- else }}
            value: {{ .Values.postgresql.service.port | quote }} 
            {{- end }}
          - name: POSTGRES_DB
            {{- if .Values.externalLogging.database }}
            value: {{ .Values.externalLogging.database }}
            {{- else }}
            value: {{  .Values.externalDatabase.database | quote }}
            {{- end }}
          - name: POSTGRES_USER
            {{- if .Values.externalLogging.user }}
            value: {{ .Values.externalLogging.user }}
            {{- else }}
            value: {{ .Values.postgresql.postgresqlUsername | quote}}
            {{- end }}
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                {{- if .Values.postgresql.enabled }}
                name: {{ template "robomotion.postgresql.fullname" . }}
                key: postgresql-password
                {{- else }}
                name: {{ printf "%s-%s" .Release.Name "external-logging-db"  }}
                key: password
                {{- end }}
          {{- else }}
          - name:  FLUENT_ELASTICSEARCH_HOST
            value: {{ .Values.elasticsearch.host }}
          - name:  FLUENT_ELASTICSEARCH_PORT
            value: {{ .Values.elasticsearch.port | quote }}
          - name: FLUENT_ELASTICSEARCH_SCHEME
            value: {{ .Values.elasticsearch.scheme }}
          {{- end }}
        ports:
        - containerPort: 24231
          hostPort: 24231
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: config-volume
          mountPath: /fluentd/etc/fluent.conf
          subPath: kubernetes.conf
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config-volume
        configMap:
          name: fluentd-conf
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
