apiVersion: v1
kind: Service
metadata:
  name: fluentd
  namespace: kube-logging
  labels:
    k8s-app: fluentd-logging
spec:
  externalTrafficPolicy: Cluster
  type: NodePort
  ports:
  - name: fluentd 
    port: 9880
    protocol: TCP
    targetPort: 9880
  selector:
    k8s-app: fluentd-logging
