{{- $host := ( index .Values.ingress.hosts 0 ) -}}
{{- $scheme := ( $host.tls | ternary "https" "http" ) -}}
{{- $apiURL := printf "%s://%s%s" $scheme ( .Values.api.ingress.hostname | default $host.name ) .Values.api.ingress.path -}}
{{- $appURL := printf "%s://%s%s" $scheme ( .Values.forms.ingress.hostname | default $host.name ) .Values.forms.ingress.path -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "robomotion-forms.fullname" . }}
  labels:
    app: {{ template "robomotion-forms.fullname" . }}
    chart: {{ template "robomotion.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: {{ .Values.forms.name }}
spec:
  selector:
    matchLabels:
      app: {{ template "robomotion-forms.fullname" . }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "robomotion-forms.fullname" . }}
    spec:
      containers:
      - name: {{ template "robomotion-forms.fullname" . }}
        image: "{{ .Values.forms.image }}:{{ .Values.forms.imageTag }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
        env:
          - name: API_URL
            value: {{ $apiURL }}
          - name: APP_URL
            value: {{ $appURL }}
      {{- if .Values.registry.secret }}
      imagePullSecrets:
      - name: {{ .Values.registry.secret }}
      {{- end }}
