apiVersion: apps/v1
kind: Deployment
metadata:
  name: robomotion-grafana
  namespace: default
  labels:
    app.kubernetes.io/name: grafana
    helm.sh/chart: grafana-5.1.1
    app.kubernetes.io/instance: robomotion
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
      app.kubernetes.io/instance: robomotion
      app.kubernetes.io/component: grafana
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grafana
        helm.sh/chart: grafana-5.1.1
        app.kubernetes.io/instance: robomotion
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: grafana
      annotations:
        checksum/secret: 06ab98bc9cdf8f43196d8658f0dfb7b9b47ac54a0ca38360fdf0b7e81758ad56
        checksum/config: 3c991eb00be5903510788f707259c76030e529841d4c82e885130c60300d599d
        checksum/dashboard-provider: 01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546b
    spec:

      serviceAccountName: robomotion-grafana
      affinity:
        podAffinity:

        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: grafana
                    app.kubernetes.io/instance: robomotion
                    app.kubernetes.io/component: grafana
                namespaces:
                  - default
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:

      securityContext:
        runAsUser: 1001
        fsGroup: 1001
        runAsNonRoot: true
      containers:
        - name: grafana
          image: docker.io/bitnami/grafana:7.3.7-debian-10-r0
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: robomotion-grafana-envvars
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: robomotion-grafana-admin
                  key: GF_SECURITY_ADMIN_PASSWORD
          volumeMounts:
            - name: grafana-ini
              mountPath: /opt/bitnami/grafana/conf/grafana.ini
              subPath: grafana.ini
            - name: data
              mountPath: /opt/bitnami/grafana/data
            - name: mail-volume
              mountPath: /opt/bitnami/grafana/public/emails
          ports:
            - name: dashboard
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/health
              port: dashboard
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /api/health
              port: dashboard
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          resources:
            limits: {}
            requests: {}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: robomotion-grafana
        - name: grafana-ini
          configMap:
            name: grafana-ini-config
        - configMap:
            name: emails
          name: mail-volume
