{{- $host := ( index .Values.ingress.hosts 0 ) -}}
{{- $scheme := ( $host.tls | ternary "https" "http" ) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "robomotion-logger.fullname" . }}
  labels:
    app: {{ template "robomotion-logger.fullname" . }}
    chart: {{ template "robomotion.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: {{ .Values.logger.name }}
spec:
  selector:
    matchLabels:
      app: {{ template "robomotion-logger.fullname" . }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "robomotion-logger.fullname" . }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
      - name: {{ template "robomotion-logger.fullname" . }}
        image: "{{ .Values.logger.image }}:{{ .Values.logger.imageTag }}"
        ports:
        - containerPort: 80
          name: http
        env:
          {{- if .Values.externalLogging.override }}
          - name: POSTGRES_HOST
            {{- if .Values.externalLogging.host }}
            value: {{ .Values.externalLogging.host | quote }}
            {{- else }}
            value: {{ template "robomotion.postgresql.fullname" . }}
            {{- end }}
          - name: POSTGRES_PORT
            {{- if .Values.externalLogging.port }}
            value: {{ .Values.externalLogging.port | quote }}
            {{- else }}
            value: {{ .Values.postgresql.service.port | quote }}
            {{- end }}
          - name: POSTGRES_DB
            {{- if .Values.externalLogging.database }}
            value: {{ .Values.externalLogging.database | quote }}
            {{- else }}
            value: {{  .Values.postgresql.postgresqlDatabase | quote }}
            {{- end }}
          - name: POSTGRES_USER
            {{- if .Values.externalLogging.user }}
            value: {{ .Values.externalLogging.user | quote }}
            {{- else }}
            value: {{ .Values.postgresql.postgresqlUsername | quote }}
            {{- end }}
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                {{- if .Values.postgresql.enabled }}
                name: {{ template "robomotion.postgresql.fullname" . }}
                key: postgresql-password
                {{- else }}
                name: {{ printf "%s-%s" .Release.Name "external-logging-db"  }}
                key: password
                {{- end }}
          {{- end }}
          - name: FLUENTD_HOST
            {{- if .Values.externalLogging.override }}
            value: {{ .Values.logger.fluentd.host | quote }}
            {{- else }}
            value: {{ .Values.logger.fluentd.hostEs | quote }}
            {{- end }}
          - name: FLUENTD_PORT
            value: {{ .Values.logger.fluentd.port | quote }}
          - name: REDIS_SCHEME
            value: {{ default "redis" .Values.redis.scheme }}
          - name: REDIS_HOST
          {{- if .Values.redis.enabled }}
            value: {{ template "robomotion.redis.host" . }}
          {{- else }}
            value: {{ .Values.externalRedis.host | quote }}
          {{- end }}
          - name: REDIS_PORT
          {{- if .Values.redis.enabled }}
            value: {{ .Values.redis.redisPort | quote }}
          {{- else }}
            value: {{ .Values.externalRedis.port | quote }}
          {{- end }}
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                {{- if .Values.redis.enabled }}
                name: {{ template "robomotion.redis.fullname" . }}
                key: redis-password
                {{- else }}
                name: {{ printf "%s-%s" .Release.Name "external-redis"  }}
                key: password
                {{- end }}
      {{- if .Values.registry.secret }}
      imagePullSecrets:
      - name: {{ .Values.registry.secret }}
      {{- end }}
