apiVersion: batch/v1
kind: Job
metadata:
  name: robomotion-onprem-init
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: set-bucket-policy
          image: "{{ .Values.onpremInit.image }}:{{ .Values.onpremInit.imageTag }}"
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args:
            - -c
            - | 
              until mc alias set robominio http://robomotion-minio.default.svc.cluster.local:9000 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY}; do
                echo "Retrying MinIO alias setup..."
                sleep 5
              done &&
              mc anonymous set public robominio/applications &&   
              echo "API_URL=https://$ROBOMOTION_HOST_NAME/api" > /tmp/7c07607d-45e7-4fc2-b1dc-7806edd1c39e/assets/.env &&
              echo "WS_URL=https://$ROBOMOTION_HOST_NAME" >> /tmp/7c07607d-45e7-4fc2-b1dc-7806edd1c39e/assets/.env &&                            
              mc cp -r /tmp/7c07607d-45e7-4fc2-b1dc-7806edd1c39e robominio/applications
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: robomotion-minio
                  key: root-user
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: robomotion-minio
                  key: root-password
          {{- range .Values.onpremInit.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
          {{- end }}
