apiVersion: batch/v1
kind: Job
metadata:
  name: robomotion-onprem-init
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: set-bucket-policy
          image: "{{ .Values.onpremInit.image }}:{{ .Values.onpremInit.imageTag }}"
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args:
            - -c
            - >
              mc alias set robominio http://robomotion-minio.default.svc.cluster.local:9000 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY} &&
              mc anonymous set public robominio/applications &&   
              echo "API_URL=$ROBOMOTION_HOST_NAME/api" > /tmp/assistant/assets/.env &&
              echo "WS_URL=$ROBOMOTION_HOST_NAME" >> /tmp/assistant/assets/.env &&              
              mc cp -r /tmp/assistant robominio/applications
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: robomotion-minio
                  key: root-user
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: robomotion-minio
                  key: root-password
          {{- range .Values.onpremInit.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
          {{- end }}