apiVersion: batch/v1
kind: Job
metadata:
  name: robomotion-onprem-init
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: set-bucket-policy
          image: gcr.io/robomotion/robomotion-onprem-init:c37bc8aae
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args:
            - -c
            - >
              mc alias set robominio http://robomotion-minio.default.svc.cluster.local:9000 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY} &&
              mc anonymous set public robominio/applications &&   
              echo "API_URL=$ROBOMOTION_HOST_NAME/api" > /tmp/7c07607d-45e7-4fc2-b1dc-7806edd1c39e/assets/.env &&
              echo "WS_URL=$ROBOMOTION_HOST_NAME" >> /tmp/7c07607d-45e7-4fc2-b1dc-7806edd1c39e/assets/.env &&              
              echo "[robominio]
              type = s3
              provider = MinIO
              env_auth = false
              access_key_id = ${MINIO_ACCESS_KEY}
              secret_access_key = ${MINIO_SECRET_KEY}
              endpoint = http://robomotion-minio.default.svc.cluster.local:9000" > /root/.config/rclone/rclone.conf &&              
              rclone copy /tmp/7c07607d-45e7-4fc2-b1dc-7806edd1c39e robominio:applications --config /root/.config/rclone/rclone.conf
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: robomotion-minio
                  key: root-user
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: robomotion-minio
                  key: root-password
          {{- range .Values.onpremInit.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
          {{- end }}