apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "robomotion-monitoring.fullname" . }}
  labels:
    app: {{ template "robomotion-monitoring.fullname" . }}
    chart: {{ template "robomotion.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: {{ .Values.monitoring.name }}
spec:
  selector:
    matchLabels:
      app: {{ template "robomotion-monitoring.fullname" . }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "robomotion-monitoring.fullname" . }}
    spec:
      containers:
      - name: {{ template "robomotion-monitoring.fullname" . }}
        image: "{{ .Values.monitoring.image }}:{{ .Values.monitoring.imageTag }}"
        ports:
        - containerPort: 9000
          name: grpc
        env:
          - name: DATABASE_IP
          {{- if .Values.postgresql.enabled }}
            value: {{ template "robomotion.postgresql.fullname" . }}
          {{- else }}
            value: {{ .Values.externalDatabase.host | quote }}
          {{- end }}
          - name: DATABASE_PORT
          {{- if .Values.postgresql.enabled }}
            value: {{ .Values.postgresql.service.port | quote }}
          {{- else }}
            value: {{ .Values.externalDatabase.port | quote }}
          {{- end }}
          - name: DATABASE_NAME
          {{- if .Values.postgresql.enabled }}
            value: {{ .Values.postgresql.auth.database | quote }}
          {{- else }}
            value: {{ .Values.externalDatabase.database | quote }}
          {{- end }}
          - name: DATABASE_USERNAME
          {{- if .Values.postgresql.enabled }}
            value: {{ .Values.postgresql.auth.username | quote }}
          {{- else }}
            value: {{ .Values.externalDatabase.user | quote }}
          {{- end }}
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                {{- if .Values.postgresql.enabled }}
                name: {{ template "robomotion.postgresql.fullname" . }}
                key: postgres-password
                {{- else }}
                name: {{ printf "%s-%s" .Release.Name "external-db"  }}
                key: password
                {{- end }}
          - name: REDIS_SCHEME
            value: {{ default "redis" .Values.redis.scheme }}
          - name: REDIS_IP
          {{- if .Values.redis.enabled }}
            value: {{ template "robomotion.redis.host" . }}
          {{- else }}
            value: {{ .Values.externalRedis.host | quote }}
          {{- end }}
          - name: REDIS_PORT
          {{- if .Values.redis.enabled }}
            value: {{ .Values.redis.redisPort | quote }}
          {{- else }}
            value: {{ .Values.externalRedis.port | quote }}
          {{- end }}
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                {{- if .Values.redis.enabled }}
                name: {{ template "robomotion.redis.fullname" . }}
                key: redis-password
                {{- else }}
                name: {{ printf "%s-%s" .Release.Name "external-redis"  }}
                key: password
                {{- end }}
          - name: CLICKHOUSE_IP
            value: {{ printf "%s-%s.%s" "clickhouse" .Release.Name "default.svc.cluster.local"  }}
          - name: CLICKHOUSE_PORT
            value: "9000"
          - name: CLICKHOUSE_USERNAME
            value: admin
          - name: CLICKHOUSE_NAME
            value: robomotion
          - name: CLICKHOUSE_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: {{ printf "%s-%s" .Release.Name "clickhouse"  }}
      {{- if .Values.registry.secret }}
      imagePullSecrets:
      - name: {{ .Values.registry.secret }}
      {{- end }}
