apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "robomotion-package.fullname" . }}-volume
  labels:
    type: local
spec:
  accessModes:
  - ReadWriteMany
  - ReadOnlyMany
  capacity:
    storage: {{ .Values.packageService.storage }}
  storageClassName: microk8s-hostpath
  hostPath:
    path: /root/packages
