apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "robomotion-scheduler.fullname" . }}
  labels:
    app: {{ template "robomotion-scheduler.fullname" . }}
    chart: {{ template "robomotion.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: {{ .Values.scheduler.name }}
spec:
  selector:
    matchLabels:
      app: {{ template "robomotion-scheduler.fullname" . }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "robomotion-scheduler.fullname" . }}
    spec:
      containers:
      - name: {{ template "robomotion-scheduler.fullname" . }}
        image: "{{ .Values.scheduler.image }}:{{ .Values.scheduler.imageTag }}"
        ports:
        - containerPort: 8080
          name: grpc
        env:
          - name: PROXY_SRV
            value: {{ template "robomotion-proxy.fullname" . }}-grpc
          - name: POSTGRES_HOST
          {{- if .Values.postgresql.enabled }}
            value: {{ template "robomotion.postgresql.fullname" . }}
          {{- else }}
            value: {{ .Values.externalDatabase.host | quote }}
          {{- end }}
          - name: POSTGRES_PORT
          {{- if .Values.postgresql.enabled }}
            value: {{ .Values.postgresql.service.port | quote }}
          {{- else }}
            value: {{ .Values.externalDatabase.port | quote }}
          {{- end }}
          - name: POSTGRES_DB
          {{- if .Values.postgresql.enabled }}
            value: {{ .Values.postgresql.auth.database | quote }}
          {{- else }}
            value: {{ .Values.externalDatabase.database | quote }}
          {{- end }}
          - name: POSTGRES_USER
          {{- if .Values.postgresql.enabled }}
            value: {{ .Values.postgresql.auth.username | quote }}
          {{- else }}
            value: {{ .Values.externalDatabase.user | quote }}
          {{- end }}
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                {{- if .Values.postgresql.enabled }}
                name: {{ template "robomotion.postgresql.fullname" . }}
                key: postgres-password
                {{- else }}
                name: {{ printf "%s-%s" .Release.Name "external-db"  }}
                key: password
                {{- end }}
          - name: STORE_ENDPOINT
          {{- if .Values.minio.enabled }}
            value: {{ template "robomotion.minio.host" . }}
          {{- else }}
            value: {{ .Values.externalObjectStore.location | quote }}
          {{- end }}
          - name: STORE_BUCKET
          {{- if .Values.minio.enabled }}
            value: {{ .Values.minio.defaultBucket.name | quote }}
          {{- else }}
            value: {{ .Values.externalObjectStore.bucket | quote }}
          {{- end }}          
          - name: STORE_ACCESSKEY
            valueFrom:
              secretKeyRef:
                {{- if .Values.minio.enabled }}
                name: {{ template "robomotion.minio.fullname" . }}
                key: root-user
                {{- else }}
                name: {{ printf "%s-%s" .Release.Name "external-object-store"  }}
                key: access-key
                {{- end }}
          - name: STORE_SECRET
            valueFrom:
              secretKeyRef:
                {{- if .Values.minio.enabled }}
                name: {{ template "robomotion.minio.fullname" . }}
                key: root-password
                {{- else }}
                name: {{ printf "%s-%s" .Release.Name "external-object-store"  }}
                key: secret-key
                {{- end }}
          - name: REDIS_SCHEME
            value: {{ default "redis" .Values.redis.scheme }}
          - name: REDIS_HOST
          {{- if .Values.redis.enabled }}
            value: {{ template "robomotion.redis.host" . }}
          {{- else }}
            value: {{ .Values.externalRedis.host | quote }}
          {{- end }}
          - name: REDIS_PORT
          {{- if .Values.redis.enabled }}
            value: {{ .Values.redis.redisPort | quote }}
          {{- else }}
            value: {{ .Values.externalRedis.port | quote }}
          {{- end }}
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                {{- if .Values.redis.enabled }}
                name: {{ template "robomotion.redis.fullname" . }}
                key: redis-password
                {{- else }}
                name: {{ printf "%s-%s" .Release.Name "external-redis"  }}
                key: password
                {{- end }}
      {{- if .Values.registry.secret }}
      imagePullSecrets:
      - name: {{ .Values.registry.secret }}
      {{- end }}
