{{- $host := ( index .Values.ingress.hosts 0 ) -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "robomotion-user-apps.fullname" . }}
  annotations:
{{- if .Values.certmanager.enabled }}
    certmanager.k8s.io/issuer: "{{ .Release.Name }}-issuer"
{{- end }}
    nginx.ingress.kubernetes.io/ssl-redirect: {{ $host.tls | quote }}
{{ toYaml .Values.ingress.annotations | indent 4 }}
spec:
{{- if $host.tls }}
  tls:
  - hosts:
    - {{ $host.name }}
    secretName: {{ $host.tlsSecret }}
{{- end }}
  rules:
  - host: {{ .Values.api.ingress.hostname | default $host.name }}
    http:
      paths:
      - path: {{ .Values.userApps.ingress.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ template "robomotion.nginx.fullname" . }}
            port:
              number: 80

